name: Setup Maven Environment
description: Common setup for Java and Maven with GitHub Packages authentication

inputs:
  java_version:
    description: 'Java version to use'
    required: false
    default: "17"
  server_ids:
    description: 'Comma-separated list of Maven server IDs to configure'
    required: false
    default: ""
  github_packages_user:
    description: 'GitHub Packages username for authentication'
    required: false
  github_packages_token:
    description: 'GitHub Packages token for authentication'
    required: false
  cache_enabled:
    description: 'Enable Maven cache'
    required: false
    default: "true"

outputs:
  servers_configured:
    description: 'List of configured Maven servers'
    value: ${{ steps.maven_auth.outputs.servers }}

runs:
  using: "composite"
  steps:
    - name: Configure Maven Authentication
      id: maven_auth
      if: ${{ inputs.github_packages_user != '' && inputs.github_packages_token != '' }}
      shell: bash
      run: |
        set -euo pipefail
        
        # Function to add server to list if not already present
        add_server() {
          local id="$1"
          local list="$2"
        
          [[ -z "$id" ]] && echo "$list" && return
        
          if [[ -z "$list" ]]; then
            echo "$id"
          elif [[ "$list" != *"$id"* ]]; then
            echo "$list,$id"
          else
            echo "$list"
          fi
        }
        
        # Build server list starting with default
        SERVERS="github,github-utilities"
        
        # Add additional servers from input
        if [[ -n "${{ inputs.server_ids }}" ]]; then
          IFS=',' read -ra EXTRA_SERVERS <<< "${{ inputs.server_ids }}"
          for raw_server in "${EXTRA_SERVERS[@]}"; do
            server_id="$(echo "$raw_server" | xargs)"  # Trim whitespace
            SERVERS=$(add_server "$server_id" "$SERVERS")
          done
        fi
        
        echo "📋 Configuring Maven servers: $SERVERS"
        echo "servers=$SERVERS" >> "$GITHUB_OUTPUT"
        
        # Create Maven settings.xml with authentication
        mkdir -p ~/.m2
        
        cat > ~/.m2/settings.xml << 'XML_HEADER'
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
        XML_HEADER
        
        # Add server configurations
        IFS=',' read -ra SERVER_ARRAY <<< "$SERVERS"
        for server_id in "${SERVER_ARRAY[@]}"; do
          cat >> ~/.m2/settings.xml << XML_SERVER
            <server>
              <id>${server_id}</id>
              <username>${MAVEN_USERNAME}</username>
              <password>${MAVEN_PASSWORD}</password>
            </server>
        XML_SERVER
        done
        
        # Close servers section (we'll close </settings> after optional repo profile)
        cat >> ~/.m2/settings.xml << 'XML_SERVERS_CLOSE'
          </servers>
        XML_SERVERS_CLOSE
        
        # Add repositories ONLY for github-utilities (via an active profile)
        if [[ ",$SERVERS," == *",github-utilities,"* ]]; then
          cat >> ~/.m2/settings.xml << 'XML_UTILITIES_REPO_PROFILE'
          <profiles>
            <profile>
              <id>github-utilities-repo</id>
              <repositories>
                <repository>
                  <id>github-utilities</id>
                  <name>GitHub Packages for Utilities</name>
                  <url>https://maven.pkg.github.com/CyborgCodeSyndicate/utilities</url>
                  <releases>
                    <enabled>true</enabled>
                  </releases>
                  <snapshots>
                    <enabled>true</enabled>
                  </snapshots>
                </repository>
              </repositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>github-utilities-repo</activeProfile>
          </activeProfiles>
        XML_UTILITIES_REPO_PROFILE
        fi
        
        # Close settings
        cat >> ~/.m2/settings.xml << 'XML_SETTINGS_CLOSE'
        </settings>
        XML_SETTINGS_CLOSE
        
        echo "GITHUB_PACKAGES_TOKEN=${MAVEN_PASSWORD}" >> "$GITHUB_ENV"
        
        # Log configuration summary
        SERVER_COUNT=${#SERVER_ARRAY[@]}
        echo "✅ Configured $SERVER_COUNT Maven server(s)"
        echo "📝 Server IDs:"
        for server_id in "${SERVER_ARRAY[@]}"; do
          echo "   - $server_id"
        done
      env:
        MAVEN_USERNAME: ${{ inputs.github_packages_user }}
        MAVEN_PASSWORD: ${{ inputs.github_packages_token }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java_version }}
        cache: ${{ inputs.cache_enabled == 'true' && 'maven' || '' }}
        overwrite-settings: false