name: Version Management
description: Compute and optionally bump project version

inputs:
  version_bump:
    description: 'Version bump type (major, minor, patch, none)'
    required: false
    default: none
  enforce_main_branch:
    description: 'Enforce that version bumps only happen on main branch'
    required: false
    default: "true"

outputs:
  current_version:
    description: 'Current project version'
    value: ${{ steps.compute.outputs.current }}
  next_version:
    description: 'Next version to use'
    value: ${{ steps.compute.outputs.next }}
  bump_type:
    description: 'Version bump type applied'
    value: ${{ steps.compute.outputs.bump }}
  branch:
    description: 'Current branch name'
    value: ${{ steps.compute.outputs.branch }}
  is_release:
    description: 'Whether this is a release version (not snapshot)'
    value: ${{ steps.compute.outputs.is_release }}

runs:
  using: "composite"
  steps:
    - name: Compute Version
      id: compute
      shell: bash
      run: |
        set -euo pipefail
        
        # Get inputs
        BUMP_TYPE="${{ inputs.version_bump }}"
        CURRENT_BRANCH="${GITHUB_REF#refs/heads/}"
        
        # Validate branch restrictions
        if [[ "${{ inputs.enforce_main_branch }}" == "true" ]] && \
           [[ "$BUMP_TYPE" != "none" ]] && \
           [[ "$CURRENT_BRANCH" != "main" ]]; then
          echo "❌ Version bump '$BUMP_TYPE' is only allowed on the main branch" >&2
          echo "   Current branch: $CURRENT_BRANCH" >&2
          exit 1
        fi
        
        # Get current version from POM
        echo "📖 Reading current version from pom.xml..."
        CURRENT_VERSION=$(mvn -q -Dexpression=project.version -DforceStdout help:evaluate 2>/dev/null || echo "")
        
        if [[ -z "$CURRENT_VERSION" ]]; then
          echo "❌ Failed to determine project version from pom.xml" >&2
          exit 1
        fi
        
        echo "   Current version: $CURRENT_VERSION"
        
        # Parse version components
        BASE_VERSION=${CURRENT_VERSION%-SNAPSHOT}
        IFS='.' read -ra VERSION_PARTS <<< "$BASE_VERSION"
        
        MAJOR=${VERSION_PARTS[0]:-0}
        MINOR=${VERSION_PARTS[1]:-0}
        PATCH=${VERSION_PARTS[2]:-0}
        
        # Calculate next version based on bump type
        case "$BUMP_TYPE" in
          major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}"
            IS_RELEASE="true"
            ;;
          minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}"
            IS_RELEASE="true"
            ;;
          patch)
            PATCH=$((PATCH + 1))
            NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}"
            IS_RELEASE="true"
            ;;
          none|*)
            # Create snapshot version with unique identifier
            GIT_SHA=$(git rev-parse --short HEAD)
            RUN_ID="${GITHUB_RUN_ID:-0}"
            NEXT_VERSION="${BASE_VERSION}-SNAPSHOT-${GIT_SHA}-${RUN_ID}"
            IS_RELEASE="false"
            ;;
        esac
        
        # Output results
        echo "📊 Version calculation results:"
        echo "   Bump type: $BUMP_TYPE"
        echo "   Next version: $NEXT_VERSION"
        echo "   Is release: $IS_RELEASE"
        
        # Set outputs
        echo "current=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"
        echo "next=$NEXT_VERSION" >> "$GITHUB_OUTPUT"
        echo "bump=$BUMP_TYPE" >> "$GITHUB_OUTPUT"
        echo "branch=$CURRENT_BRANCH" >> "$GITHUB_OUTPUT"
        echo "is_release=$IS_RELEASE" >> "$GITHUB_OUTPUT"

    - name: Update POM Version
      shell: bash
      run: |
        echo "📝 Updating pom.xml to version: ${{ steps.compute.outputs.next }}"
        mvn -B versions:set \
          -DnewVersion=${{ steps.compute.outputs.next }} \
          -DprocessAllModules=true \
          -DgenerateBackupPoms=false \
          --no-transfer-progress